vich_uploader:
    db_driver: orm

    mappings:
        performer_image:
            uri_prefix: /images/performers
            upload_destination: '%kernel.project_dir%/public/images/performers'
        performance_image:
            uri_prefix: /images/performances
            upload_destination: '%kernel.project_dir%/public/images/performances'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
