language: php
php:
    - '7.2'
before_script:
    - if [ -d "./.idea" ]; then echo "Forbidden idea folder found !"; exit 2; fi
    - if [ -d "./.env.local" ]; then echo "Forbidden configuration file found !"; exit 2; fi
install:
    - composer require squizlabs/php_codesniffer
    #- composer require phpunit
script:
    - ./vendor/bin/phpcs
    #- ./vendor/bin/phpunit
branches:
  only:
      - master
      - dev